From php:8.2-apache 

WORKDIR /var/www/html
COPY . .

RUN apt-get update && apt-get install -y \
        libonig-dev \
        libzip-dev \
        unzip \
    && docker-php-ext-install pdo_mysql \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 8000

WORKDIR CMS

CMD php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000
